### ISSUE TITLE
What's up with the plan here?

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#1]
Hi Nicolas,

Could you let us know what you are thinking with the new class and libraries?  It will make it easier for us to participate.

Thanks,
Brian

**Comment by npcottaris** [comment]
Hello Brian,

Sorry for not explaining my intentions before. I wanted to report something after my tests were concluded. But anyhow here are my findings to this point.
- The only way (that I could find) for Matlab to upload data to a server is via `mput`. However,
  `mput` uses a regular ftp protocol, which _crimson.stanford.edu_ seems to not allow: it times out as seen in  following screendump:

```
Ithaka:~ nicolas$ ftp crimson.stanford.edu
ftp: Can't connect to `171.64.204.31': Operation timed out
ftp: Can't connect to `crimson.stanford.edu'
ftp> 
```

On the other hand, _crimson.stanford.edu_  does allow `sftp` connections as seen in the following screendump.

```
Ithaka:~ nicolas$ sftp crimson.stanford.edu
nicolas@crimson.stanford.edu's password: 
Connected to crimson.stanford.edu.
sftp> 
```
- So for uploading validation data to _crimson.stanford.edu_ we have to use an `sftp` protocol. 
- As far as I could determine, Matlab does not have any native functionality for sftp connections.
- To solve this issue, I searched the internet and found a standlone (no dependencies) Java library (named `ganymed-ssh2`) which implements the SSH-2 protocol, which includes sftp. 
- After some fussing, I was able to call functions of that library from Matlab and successfully uploaded files and created directories on _crimson.stanford.edu_  all from within Matlab. 
- So, I uploaded the library and its documentation to `RemoteDataToolbox/external`.
- I also create a Matlab class, `@RemoteDataHandler`, for interfacing with this library. Using `@RemoteDataHandler`, a user can upload files to _crimson.stanford.edu_ via sftp as follows:

```
% Instantiate a @RemoteDataHandler object for user nicolas on server crimson.stanford.edu
validationRemoteDataHandler = RemoteDataHandler(...
        'serverName', 'crimson.stanford.edu',...
        'userName', 'nicolas');

% Start an SFTP session to transmit the files
validationRemoteDataHandler.startSFTPsession();

% send local file1 to the remote testDirectory3
destinationOnServer = 'validation/SCIEN/ISETBIO/fullvalidation/testDirectory3';
validationRemoteDataHandler.sendFile(localFileName1, destinationOnServer);

% send local file2 to the remote testDirectory4
destinationOnServer = 'validation/SCIEN/ISETBIO/fullvalidation/testDirectory4';
validationRemoteDataHandler.sendFile(localFileName2, destinationOnServer);

% terminate the sftp session and close the connection to the server
validationRemoteDataHandler.terminateSFTPsession();
validationRemoteDataHandler.shutdown;
```
- The executive script `v_SFTPConnection.m` in `RemoteDataToolbox/validation/scripts` demonstrates this.
- I did several uploads with large files and no uploading issues whatsoever.
- The only unresolved issue I have is that files generated by one user (me) cannot be overwritten by other users (David). But this is most likely a permissions issue.

This is all I have. I think this solution looks promising for uploading validation data to _crimson.stanford.edu_. Downloading data should be handled easily via  Matlab's native functionality, i.e., `urlwrite`, `websave` etc.

**Comment by DavidBrainard** [comment]
We might want to rename this class as SFTPDataHandler or some such, as I can imagine it would be useful by itself sometimes and that we may want wrappers around it that implement whatever more general functionality we decide we want.

DB

> On Apr 26, 2015, at 1:03 PM, Nicolas Cottaris notifications@github.com wrote:
> 
> Hello Brian,
> 
> Sorry for not explaining my intentions before. I wanted to report something after my tests were concluded. But anyhow here are my findings to this point.
> 
> The only way (that I could find) for Matlab to upload data to a server is via mput. However, mput uses a regular ftp protocol, which crimson.stanford.edu seems to not allow: it times out as seen in following screendump:
> Ithaka:~ nicolas$ ftp crimson.stanford.edu
> ftp: Can't connect to `171.64.204.31': Operation timed out
> ftp: Can't connect to`crimson.stanford.edu'
> ftp> 
> On the other hand, crimson.stanford.edu does allow sftp connections as seen in the following screendump.
> 
> Ithaka:~ nicolas$ sftp crimson.stanford.edu
> nicolas@crimson.stanford.edu's password: 
> Connected to crimson.stanford.edu.
> sftp> 
> So for uploading validation data to crimson.stanford.edu we have to use an sftp protocol.
> As far as I could determine, Matlab does not have any native functionality for sftp connections.
> To solve this issue, I searched the internet and found a standlone (no dependencies) Java library (named ganymed-ssh2) which implements the SSH-2 protocol, which includes sftp.
> After some fussing, I was able to call functions of that library from Matlab and successfully uploaded files and created directories on crimson.stanford.edu all from within Matlab.
> So, I uploaded the library and its documentation to RemoteDataToolbox/external.
> I also create a Matlab class, @RemoteDataHandler, for interfacing with this library. Using @RemoteDataHandler, a user can upload files to crimson.stanford.edu via sftp as follows:
> % Instantiate a @RemoteDataHandler object for user nicolas on server crimson.stanford.edu
> validationRemoteDataHandler = RemoteDataHandler(...
>         'serverName', 'crimson.stanford.edu',...
>         'userName', 'nicolas');
> 
> % Start an SFTP session to transmit the files
> validationRemoteDataHandler.startSFTPsession();
> 
> % send local file1 to the remote testDirectory3
> destinationOnServer = 'validation/SCIEN/ISETBIO/fullvalidation/testDirectory3';
> validationRemoteDataHandler.sendFile(localFileName1, destinationOnServer);
> 
> % send local file2 to the remote testDirectory4
> destinationOnServer = 'validation/SCIEN/ISETBIO/fullvalidation/testDirectory4';
> validationRemoteDataHandler.sendFile(localFileName2, destinationOnServer);
> 
> % shutdown the sftp session and close the connection to the server
> validationRemoteDataHandler.terminateSFTPsession();
> validationRemoteDataHandler.shutdown;
> The executive script testConnection.m in RemoteDataToolbox/scripts demonstrates this.
> I did several uploads with large files and no uploading issues whatsoever.
> The only unresolved issue I have is that files generated by one user (me) cannot be overwritten by other users (David). But this is most likely a permissions issue.
> This is all I have. I think this solution looks promising for uploading validation data to crimson.stanford.edu. Downloading data should be handled easily via Matlab's native functionality, i.e., urlwrite, websave etc.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/isetbio/RemoteDataToolbox/issues/1#issuecomment-96409422.

# 

David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
Yes, we could rename it. My original plan was to add downloading functionality as well, so that users can do both uploading and downloading via interactions with one object.
N.

**Comment by wandell** [comment]
I had a little time to return to this toolbox the last couple of days.  I might have done something useful.  Here is a brief summary of my understanding.

@NP is thinking about issues pertaining to uploading.  That's good.  I am not thinking about that at all.

I created an object (@rdata) that has methods that work with the site Michael Perry set up.  I am in need of this functionality for several related projects (vistasoft, ISET, ISETBIO).  So, I think our plan of having this live separately (like UnitTestToolbox) is good.

The feel of the object is this:  rd = rdata('baseDirectory',URL);  Upon creation the object reads the Table of contents at the remote site.  The TOC is built by a function called rdSiteTOC.

The rdata object can open up a web-browser to read through the remote site.  It has methods to
  (a) download a file, or 
  (b) download a directory from the remote site. 
  (c) return a url to a file on the remote site.  

We will surely add more methods to the object as we realize what we really want, and you will tell me other things I might have done to organize it.  There are various OK things and plenty of pieces of code in there that should be better (related to searching).

My next goal is to replace the 'rdata' routine in ISETBIO with something that is specific to ISETBIO and uses this RemoteDataToolbox instead.  That will let me see what functionality I can take advantage of.

**Comment by DavidBrainard** [comment]
In service of this, I think I figured out why I couldn’t sync to crimson and got it working.  I believe the full validation data for isetbio is now up to date on crimson.

One thing I think we will want is for this code to get its locations and other configurable parameters thought a set of preferences which can be set differently for different projects.

We will also have to think about how to integrate it into the UnitTestToolbox, so that the methods used there to read validation data can take advantage of the methods.

DB

**Comment by np** [comment]
@wandell: I guess you meant to refer @npcottaris not @np.

**Comment by benjamin-heasly** [comment]
Any objection to closing this issue and directing readers to our discussion in #4 ?

**Comment by DavidBrainard** [comment]
OK w/ me.

David

> On Nov 18, 2015, at 12:26 PM, Ben Heasly notifications@github.com wrote:
> 
> Any objection to closing this issue and directing readers to our discussion in #4 https://github.com/isetbio/RemoteDataToolbox/issues/4 ?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/isetbio/RemoteDataToolbox/issues/1#issuecomment-157786830.

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by wandell** [comment]
Appreciate all the action at your end.

Traveling.  

Close it up

Brian

**Comment by benjamin-heasly** [comment]
Please see discussion in #4 and associated google document.
