### ISSUE TITLE
Read and write raw URLs

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/RemoteDataToolbox#14]
The Gradle / Maven / Archiva model is one good way to read and publish artifact data.  But it's not the only way.  RemoteDataToolbox should also be able to read and write artifacts from raw URLs.

Refactor the API implementation to allow different network "strategies":
- the Gradle / Maven / Archiva strategy
- plain-old RESTful reading and writing strategy

The plain-old RESTful strategy might not support all features.  For example, keyword searching and directory listing wold depend on server configuration details which the toolbox won't always know about.

**Comment by benjamin-heasly** [comment]
#10 was a first step, replacing terminology of "maven group" with more general "remote path".

**Comment by wandell** [comment]
Seems like we have moved on and this should be closed.
