### ISSUE TITLE
Description field not updating

### ISSUE THREAD

**Issue by npcottaris** [isetbio/RemoteDataToolbox#30]
If an artifact is deleted and the pushed again with a different description field, it appears that the description field is not updated.
Is this some kind of cache-related issue?

Refreshing the browser does not solve the problem.

**Comment by benjamin-heasly** [comment]
I noticed the web ui was slow to update the description, but eventually
did.  I agree it seems like a cache problem.  Would have to look into it.

But when I fetched the same artifact the description was actually correctly
updated.

Are you having this issue just in the web ui or for fetched artifacts as
well?

**Comment by npcottaris** [comment]
I have not tried fetching yet. Just uploading via RDT and checking via web ui. 
I did some more testing. Sometimes is updates within minutes, other times it can take much much longer...

Thanks.

**Comment by benjamin-heasly** [comment]
I'm closing this issue with a pointer to #47, which aims to keep the discussion going.
