### ISSUE TITLE
Archiva repositories - request for repository creation

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#31]
I spent a little time trying to understand the concepts in Archiva.  If I understand things (not clear that I do) then it appears that there is
- A fundamental notion of a repository
- Within each repository we can organize resources (like directories) with either the . syntax or the / syntax

Based on this understanding, I managed to screw around with the RdtClient object configuration slots and add a file or two to the isetbio repository.  So, that gave me enough confidence to post this issue.

OK, so here is the point.  It seems to me that someone like me can NOT create a repository. So, here is a request for two additional repositories, one called scien and another called vistasoft.  We will use these for data that are outside the scope of the ISETBIO project, but potentially useful to several of the members.  

I think that Ben needs to create this - is that right?  I screwed around with the main web page interface and couldn't see how to create one myself.  But ...

Thanks!

**Comment by benjamin-heasly** [comment]
Agreed about the notion of repository.  Here is how I see it:
- an Archiva server instance
- contains some number of repositories
- each of which contains various groups and subgroups
- each of which contains various artifacts

And what Archiva calls a "group" we usually call a "folder".

And what Archiva calls an "artifact" we usually call a "file".

**Comment by benjamin-heasly** [comment]
Yes, only some users can create new repositories.  wandell is now one of them!

If anyone needs more permissions, I'm happy to add them.  If you make an issue like this or email benjamin.heasly@gmail.com, I should see it.

At the moment, here are the Admin users:
- ben (me)
- wandell
- cottaris
- dhb

**Comment by benjamin-heasly** [comment]
These now exist:
- <a href="http://52.32.77.154/#browse~scien">scien</a>
- <a href="http://52.32.77.154/#browse~vistasoft">vistasoft</a>

They should be ready for business!  If they seem not to be RFB, please LMK and I'll try to fix!
