### ISSUE TITLE
Archiva repository browsing

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#32]
I also noticed that the UI interface to the repository varies depending on the syntax of the URL.   
- There is a format http://FOO/#browse~isetbio/DOT-SYNTAX and 
- An alternative URL syntax http://FOO/repository/isetbio/SLASH-SYNTAX

We use the SLASH-SYNTAX with the rdtClient.  
The basic Archiva interface runs on the DOT-Syntax. 
Not sure which one we prefer.  Maybe we need both as options?

**Comment by benjamin-heasly** [comment]
Yeah, this is kind of confusing / annoying.  The two interfaces have mostly the same information, but
- DOT-SYNTAX is easier to navigate and provides a nicer-to-read summary.
- SLASH-SYNTAX is the only one that shows the size of a file, and the only one where you can see the raw file URL and do a manual browser download.

So I think having both as options is good.

From the Matlab client, I'm not sure how we should present the option in a nice way.  I think simply requiring the user to choose one or the other could be confusing and cause users to say, "Well, how should I know which one?  I haven't tried it yet".

What if `openBrowser()` opens both the DOT-SYNTAX url and the SLASH-SYNTAX url at the same time?

**Comment by benjamin-heasly** [comment]
David and I discussed this.  We think the default behavior should be to open the relatively pleasant DOT-SYNTAX url.  [For example](http://52.32.77.154/#artifact/validation.full.wavefront/wvfZernikePolynomials).

And we can add an optional parameter to specify relatively ugly but more informative SLASH-SYNTAX url.  [For example](http://52.32.77.154/repository/isetbio//validation/full/wavefront/wvfZernikePolynomials/).

Later we might find some clever way to decide what the user probably wants, and choose automatically.  That could be nice.  But for now, it's just an option.

**Comment by wandell** [comment]
I added a 'fancy' option to the openBrowser('fancy',true) that uses the pleasant DOT-SYNTAX url.  What I added was very crude, but helpful enough to just get someone started in the right repository with the appropriate syntax.  If we decide to invest more effort in this, OK.  But I think we are done for now and hence I am closing this.
