### ISSUE TITLE
HyperSpectral images databases

### ISSUE THREAD

**Issue by npcottaris** [isetbio/RemoteDataToolbox#33]
Hello,

Last week I uploaded three databases of hyperspectral images as isetbio scenes: 
- http://52.32.77.154/#browse/resources.scenes.hyperspectral.harvard_database
- http://52.32.77.154/#browse/resources.scenes.hyperspectral.manchester_database
- http://52.32.77.154/#browse/resources.scenes.hyperspectral.penn_database

Today, I noticed that someone generated a fourth database
- http://52.32.77.154/#browse/resources.scenes.hyperspectral.scien_database
  and uploaded one scene (Feng_Office-hrs)

I am wondering what (if any) that someone's plans are regarding uploading the hyperspectal images found in https://scien.stanford.edu/index.php/hyperspectral-image-data/. I am asking because I was planning on converting these images and uploading them within the next couple of days.

Thanks,
Nicolas

**Comment by wandell** [comment]
Hi,

That was me trying to learn how to control the RdtClient.  Perhaps you saw the two other issues I wrote last night.  

Thanks for putting up the SCIEN images.  We can delete the one I stuck up there if it doesn't fit with your labeling and/or curation.  Let me know if you want me to do it.

Related - Joyce was fixing one of the hyperspectral scenes yesterday.  She will add fix the link to that file, probably today.

In working with on that file, we realized that normally we store these very large hyperspectral scenes using about 10-12 basis functions.  This dramatically reduces the file size but has very little impact on the accuracy of the representation.  The sceneFromFile function discovers this format and converts the basis function representation into the scene structure. 

We were thinking of recommending that you store the hyperspectral data that way. But the downside would be that the other databases store the data using the 'scene' object.  Left unchanged, we would read the hyperspectral data with 'sceneFromFile' but the other data using 'load', and that would be annoying.

So, we thought to add in a small check at the beginning of 'sceneFromFile' which asked whether there is a variable named 'scene' inside the file, and if so to return that variable. If there is no such variable, but rather the file contains the 'photons','comments', and so forth, then carry on as usual. If we make that change, we can load all of the data you have curated using the sceneFromFile command.

Does that seem right to you?

Brian

**Comment by npcottaris** [comment]
Hi Brian,

Yes, I saw the 2 issues you posted last night, but I was not 100% sure whether it was you or someone else from your lab who uploaded the SCIEN image. :). Also I did not know what the plan for the SCIEN dataset was.

The proposed check in sceneFromFile sounds good. An alternative would be to keep both data sets in separate directories with parallel structure. That will increase the space occupied, but it may have some advantages. 
- The compressed version of the scenes would be fine for 99% of the applications.  Most users would download these files, thereby saving time and hard disk space.
- Someone who would like to simulate how axial chromatic aberration of natural scene stimuli may affect the estimated cone inputs to neurons of the magnocellular pathway would like to have access to the full data set. This is because the strong contrast gain control of MC neurons would amplify small artifactual retinal cone contrasts generated by axial chromatic aberration, thereby having a big effect on the neurons' responses. If the user had access to scenes with only 10-12 basis functions, I am thinking that the computed axial chromatic aberration effects may be not as pronounced as with the full data set. 

What do you think? Are these good enough reasons for having parallel data directories ?

Nicolas

**Comment by npcottaris** [comment]
_Brian Wandell said:  So, we thought to add in a small check at the beginning of 'sceneFromFile' which asked whether there is a variable named 'scene' inside the file, and if so to return that variable. If there is no such variable, but rather the file contains the 'photons','comments', and so forth, then carry on as usual. If we make that change, we can load all of the data you have curated using the sceneFromFile command._

Hi Brian,

In implementing my end of this, I noticed that `sceneToFile`-> `ieSaveMultiSpectralImage` and `sceneFromFile` do not save/load any spatial information regarding the scene. It would be nice, and critical for our simulations,  if they were modified so as to save the horizontal `field of view` and `distance` fields.
Do you want me to do these changes, or would you prefer to do them yourself?

Thanks,
Nicolas

**Comment by wandell** [comment]
I will try to take care of these changes in the next few hours.  

Do note that in all cases we allow the field of view and distance to be adjusted by the user.  So, even though we initialize them, that will only be a starting guide.

**Comment by npcottaris** [comment]
Thanks Brian!
And yes, I am aware that the user can change this info, but my intent is to create isetbio scenes whose default properties match, or are as close as possible to, the shooting conditions.

Nicolas

**Comment by wandell** [comment]
I made the changes in ISETBIO to sceneFromFIle, sceneToFile, and ieSaveMultiSpectralImage.  These are now pushed (aggressive of me ... eeek) into the master branch.

Here is the script I used to test the functions.  I put this script in my 'local' directory for testing.

%% Test script for the sceneFromFile changes

ieInit

% I have a local directory where I test stuff that is not included in the
% git repository.
chdir(fullfile(isetbioRootPath,'local'));

%% Create and read a scene variable from the file

% This is the new feature
scene = sceneCreate;
save('testS','scene');

s = sceneFromFile('testS');
isequal(s,scene)  % Should be the same

%%  Read in a mat multispectral file

% Check that the old stuff worked
fName = 'StuffedAnimals_tungsten-hdrs.mat';
scene = sceneFromFile(fName,'multispectral');
ieAddObject(scene); sceneWindow;

%% Create a file from RGB data

RGB = ieClip(255*rand(10,10,3),0,255);
scene = sceneFromFile(RGB,'rgb');
ieAddObject(scene); sceneWindow;

%% Now try sceneToFile with the scene data

% This tests whether the new 'fov' and 'dist' read/write works
vExplained = sceneToFile('testS2',scene);
scene2 = sceneFromFile('testS2','multispectral');
ieAddObject(scene2); sceneWindow;

%%

**Comment by npcottaris** [comment]
Fantastic. Checked with the StanfordMemorial, SanFrancisco, StanfordTower, and StanfordDish images and the changes work as advertised !

Thanks again.

**Comment by benjamin-heasly** [comment]
@npcottaris @wandell any objection if I go ahead and close this issue?

**Comment by npcottaris** [comment]
Fine by me.
