### ISSUE TITLE
Documentation tidy up

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/RemoteDataToolbox#39]
The RDT documentation is a bit out of date now -- for example refers to a development rather than to the master branch both for RDT and for UnitTestToolbox and isetbio.

The isetbio documentation probably also needs updating to indicate that you need RDT to run the validations, and the UnitTestToolbox documentation will also need some updating to refer to the RDT.

**Comment by benjamin-heasly** [comment]
Can you be more specific about which documentation?

**Comment by DavidBrainard** [comment]
For RDT, I was looking at the wiki "Instructions to try out the RemoteDataToolbox.  Things I noticed were that it refers to the latest version as being on branch "bshApi2", and similarly refs to branches "rdtValidation" for UnitTestToolbox and isetbio.  I think that probably the RDT documentation only needs to say that the RDT is integrated with UnitTestToolbox and isetbio, and then refer to the documentation there for how that integration works.

I didn't look at the UTT documentation, but I suspect it needs a little updating to explain how to configure it for use with RDT.  

Similarly, I suspect that the isetbio Install (and maybe "Getting Started) wiki documentation needs to indicate that you need to install the RDT as well as the UTT to run the validations.

**Comment by benjamin-heasly** [comment]
[Instructions-to-try-out-the-RemoteDataToolbox](https://github.com/isetbio/RemoteDataToolbox/wiki/Instructions-to-try-out-the-RemoteDataToolbox) now points to the main branches, not development branches like bshApi2 and rdtValidation.

So that is a start.

**Comment by benjamin-heasly** [comment]
I am closing this issue because it's old.  If we need to do more work in this area, let's create a new issue.  Also, Brian wrote a lot of documentation for on the wiki.
