### ISSUE TITLE
Using RDT in validation scripts (and more generally)

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/RemoteDataToolbox#40]
I took the cone recording data out of isetbio and published it on the archiva server, setting up a path in the isetbio repository resources/data/experimental/cones.

This is how I'm accessing it from inside the validation script.

validationPrefs = 'isetbioValidation';
client = RdtClient(getpref(validationPrefs,'remoteDataToolboxConfig'));
client.crp('resources/data/experimental/cones');
[eyeMovementExample, eyeMovementExampleArtifact] = client.readArtifact('eyeMovementExample', 'type', 'mat');

By convention, the .mat file contains a single struct called 'data', so that then the data are accessed as (e.g.) eyeMovementExample.data.Mean.

I think my question is, is this a good convention to start with?

Note that this works because there is already a preference group 'isetbioValidation' which has a pointer to the json file that points at the archiva repository, that's how the validation scripts know how to find their validation data.  It is possible we want some more general preference for other data reads when using isetbio.  For example, perhaps there should just be an isetbio preference group that sets everything that isetbio needs to know about up, rather than just a preference for validations.  That might be more intuitive.

And we might want some sort of readData wrapper routine, that knows how to find resources that are local within isetbio but goes out to the server when it can't find them.  When we write that, I am hoping we can organize the data that is within isetbio more rationally (that is, move it outside of the isettools folder.

And I'm not sure about the right convention for what should be inside .mat files.  This particular one already had everything within a structure and I simply changed the name of the structure to be 'data' and thus more generic.

I have the code that publishes the data to the server outside of isetbio, and in a way that I can pretty easily change the convention of the data path, if what I chose doesn't seem correct.  Probably it would make sense to set the paths up via preferences as well, so that if we change our minds later it will be easy to keep things working.

**Comment by benjamin-heasly** [comment]
I am closing this issue because it's old.  If we need to do more work in this area, let's create a new issue.
