### ISSUE TITLE
Feedback from RDT client regarding the source of the retrieved artifact

### ISSUE THREAD

**Issue by npcottaris** [isetbio/RemoteDataToolbox#43]
It would be nice if the RDT client returned a third variable that indicated whether the requested artifact was retrieved from the local cache or via a remote fetch. 

The reason that this would be useful is that the subsequent processing chain may depend on that source. For example, if a scene was retrieved locally, and its optical image was already computed and stored locally, we do not need to recompute it.

Nicolas

**Comment by benjamin-heasly** [comment]
While working on #41, something like this came out almost for free.

As of 041a694db377d91af09c5bc136d296fac0385196, `rdtReadArtifact()`, `rdtReadArtifacts()`, and their counterparts in `RdtClient`, return a third variable which is a cell array of urls for artifacts that were actually downloaded (i.e. not already in the local cache).

For a single artifact, you could check whether this cell array is empty.  For multiple artifacts, you'd have to do some rummaging around to match up the downloaded urls with the artifact urls.

**Comment by benjamin-heasly** [comment]
@npcottaris does this change meet your needs?  If so, may I close this issue?

**Comment by npcottaris** [comment]
Yes, although I have not tested, it seems like it will do the job.
Closing the issue.
Thanks!
