### ISSUE TITLE
Multiple files in a single artifact

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/RemoteDataToolbox#53]
v_rgcExternal.m in the rgc branch of isetbio reads four artifacts using the RDT, where each artifact has one file. Would it be possible to combine those four files into one artifact?

**Comment by benjamin-heasly** [comment]
Could you paste some artifact urls or a code snippet here?

**Comment by jamesgolden1** [comment]
Perhaps there is an easy way to combine the files into one artifact by slightly modifying the code that published them?

The four artifacts can be found here:

http://52.32.77.154/#browse/resources.data.rgc

Here is the code from v_rgcExternal.m that reads one of the files:

client = RdtClient('isetbio');
% client.credentialsDialog();
client.crp('resources/data/rgc')
[data, artifact] = client.readArtifact('xvalall', 'type', 'mat');

Here is code that published them:

filepath = pwd;
% filename1 = [filepath 'xvalall.mat'];
% filename1 = [filepath 'testmovieshort.mat'];
% filename1 = [filepath 'parasol_on_1205.mat']; 
% filename1 = [filepath 'pairspikeall.mat'];  
%% Create a client object with project configuration and credentials.
client = RdtClient('isetbio');
client.credentialsDialog();
% change to the "remote path" where we want to publish the artifact
client.crp('/resources/data/rgc')
% each artifact must have a version, the default is version '1'
version1 = '1';
% supply the configuration, which now contains publishing credentials
artifact = client.publishArtifact(filename1, 'version', version1);
client.openBrowser;

**Comment by DavidBrainard** [comment]
Can you say a little more about what you are tring to accomplish with this?  I’m not sure whether we want
to build the combining into RDTB, as opposed to simply manually concatenating the contents of the four .mat files
into one and publishing that.  I think it depends on how often this will occur, or whether there are times when you
want a group with one call and other times where you just want a piece of the group.

On Jan 14, 2016, at 6:59 PM, jamesgolden1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Perhaps there is an easy way to combine the files into one artifact by slightly modifying the code that published them?

The four artifacts can be found here:

http://52.32.77.154/#browse/resources.data.rgc

Here is the code from v_rgcExternal.m that reads one of the files:

client = RdtClient('isetbio');
% client.credentialsDialog();
client.crp('resources/data/rgc')
[data, artifact] = client.readArtifact('xvalall', 'type', 'mat');

Here is code that published them:

filepath = pwd;
% filename1 = [filepath 'xvalall.mat'];
% filename1 = [filepath 'testmovieshort.mat'];
% filename1 = [filepath 'parasol_on_1205.mat'];
% filename1 = [filepath 'pairspikeall.mat'];

%% Create a client object with project configuration and credentials.
client = RdtClient('isetbio');
client.credentialsDialog();
% change to the "remote path" where we want to publish the artifact
client.crp('/resources/data/rgc')
% each artifact must have a version, the default is version '1'
version1 = '1';
% supply the configuration, which now contains publishing credentials
artifact = client.publishArtifact(filename1, 'version', version1);
client.openBrowser;

**Comment by wandell** [comment]
I think we decided that multiple files with different extensions (types) could be in a single artifact (when they have the same base name).  But otherwise, it will be one file per artifact.  So, I am closing.
