### ISSUE TITLE
t_rdtExample.m

### ISSUE THREAD

**Issue by rosemary-le** [isetbio/RemoteDataToolbox#56]
```
No public field PartialMatching exists for class inputParser.
```

is the weird error I'm getting when I run the first line of the tutorial. Might it be something simple I'm missing?  It's strange to me because KeepUnmatched and CaseSensitive are found as properties of inputParse, and the Matlab help page does list PartialMatching as a valid field.

This is the complete error message:

```
No public field PartialMatching exists for class inputParser.

Error in rdtInputParser (line 17)
parser.PartialMatching = false;

Error in rdtSearchParentFolders (line 21)
parser = rdtInputParser();

Error in rdtConfiguration>configFromJson (line 110)
projectConfig = rdtSearchParentFolders(jsonFileName, pwd());

Error in rdtConfiguration (line 52)
        [configArgs{1}, flavor] = configFromJson(arg);

Error in RdtClient (line 24)
            obj.configuration = rdtConfiguration(configuration);

Error in t_rdtExample (line 26)
rd = RdtClient('vistasoft');
```

**Comment by wandell** [comment]
Version of Matlab?  When I run p = inputParser, there is a p.PartialMatching completes.  I am running R2013b, version 8.2

> > p = inputParser;
> > p.PartialMatching=false

p = 

  inputParser with properties:

```
   FunctionName: ''
  CaseSensitive: 0
  KeepUnmatched: 0
PartialMatching: 0
   StructExpand: 1
     Parameters: {1x0 cell}
        Results: [1x1 struct]
      Unmatched: [1x1 struct]
  UsingDefaults: {1x0 cell}
```

**Comment by rosemary-le** [comment]
Ah. I have Matlab 2012b, Version 8.0, which only fills in 4 fields of the inputParser object:
Been meaning to update in any case ...

```
>> p = inputParser

p = 

Input Parser object with:
CaseSensitive: false
StructExpand : true
KeepUnmatched: false
FunctionName : ''
```

**Comment by wandell** [comment]
Let's let Ben figure out what he thinks is best.  It may be that the group decides we only support 2013 and beyond.  In the mean time, can you update your Matlab?

Closing ... thanks for pointing this out!

**Comment by benjamin-heasly** [comment]
Hi all,

I think the PartialMatching option is not critical.  So we could add a version check and only specify PartialMatching when version >= R2013b/8.2.

I'll make a quick PR for this.

**Comment by benjamin-heasly** [comment]
Here is a small PR for this:  https://github.com/isetbio/RemoteDataToolbox/pull/58
