### ISSUE TITLE
AWS cost

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/RemoteDataToolbox#60]
Our January bill was $145.49, so about $1800/year at that rate.  I think that is fine but we will continue to keep an eye on monthly charges.

This issue will not quite self destruct after reading, but almost (that is, I'll close it pretty soon.)

**Comment by benjamin-heasly** [comment]
Here's a picture I scraped off the AWS billing console.
![brainard-archiva-aws-usage-jan-2016](https://cloud.githubusercontent.com/assets/1950775/12931775/5c00da24-cf4d-11e5-8c1e-71a4210877fc.png)

Almost all of the cost was from EC2.  This includes the server itself and also the EBS data volume.
