### ISSUE TITLE
Force Gradle to Check for Artifact Updates

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/RemoteDataToolbox#65]
It seems like our Matlab/Gradle client is not always detecting updates to artifacts on the server.  Instead it seems to be using locally cached stale versions of the artifacts.

We should fix the Matlab and/or Gradle code to make sure we don't miss changes like this.

**Comment by benjamin-heasly** [comment]
Gradle has the concept of a "changing" artifact.  We can probably tell Gradle that all of our artifacts are "changing".  In addition, we can tell Gradle to check for changes on every fetch.

I think this Gradle code is roughly what we want, in `fetch.gradle`:

```
configurations.all {
    // check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
  dependencies {
    compile group: "group", name: "projectA", version: "1.1-SNAPSHOT", changing: true
}
```

Which comes from a [Gradle forum](https://discuss.gradle.org/t/how-to-get-gradle-to-download-newer-snapshots-to-gradle-cache-when-using-an-ivy-repository/7344/9).

**Comment by DavidBrainard** [comment]
Not only that but if you explore the local artifacts, say:

```
list = rdtListLocalArtifacts(getpref('isetbio', 'remoteDataToolboxConfig'), 'validation', 'artifactId', 'oi')
```

I get 6 entries whose local paths are:

```
/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.fast.optics/oi/run00001/3e0df3c57d7fb15e3159e056a5c7bc6c1f8feadf/oi-run00001-mat.mat


/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.fast.optics/oi/run00001/9f6acf55a26e3f5a1d3a40bcd257ff37676a34f5/oi-run00001-mat.mat

/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.fast.optics/oi/run00001/ddc89ba698051b31ad42787d3803433c48220802/oi-run00001.pom


/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.full.optics/oi/run00001/1a4caad117f1e6fe0447c4620a1da819d6943d64/oi-run00001-mat.mat


/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.full.optics/oi/run00001/7bc031ecb980a6e461a14c9321c9f4e5992dd849/oi-run00001-mat.mat


/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.full.optics/oi/run00001/fc526dda0846ee985e537b02ac1fb01153b7af43/oi-run00001.pom
```

i.e., two copies of the 'fast' and the 'full' validation files, all of which have stale creation and modification dates (Jan 8).

**Comment by DavidBrainard** [comment]
The above message (as well as this one) was sent by Nicolas sitting on David's computer.

**Comment by benjamin-heasly** [comment]
Here is a new [PR](https://github.com/isetbio/RemoteDataToolbox/pull/67) which I think addresses this issue.

Now, artifact updates from one client should be detected and downloaded by other clients, on the next read.

I added a test case for this.  The test uses two local caches to simulate two clients.  This test failed under the old code.  Then I worked on the code, and the test passed.  So that's a good change.

But still we should do a test of detecting changes across the real Internet.  Anyone want to hang out with me on Skype and do a manual test?

**Comment by benjamin-heasly** [comment]
Regarding those 6 cache entries -- 

I think they're OK, as far as they go.  It makes sense to me that the local cache would contain multiple copies of each artifact, each with its own checksum, if that machine has published updates to the artifacts.

As I understand it, the PR above will cause Gradle to detect and download yet another, newer version of the same artifacts.

**Comment by DavidBrainard** [comment]
I can do this with you at 10:00 this morning.

DB

On Mar 8, 2016, at 5:50 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Here is a new PRhttps://github.com/isetbio/RemoteDataToolbox/pull/67 which I think addresses this issue.

Now, artifact updates from one client should be detected and downloaded by other clients, on the next read.

I added a test case for this. The test uses two local caches to simulate two clients. This test failed under the old code. Then I worked on the code, and the test passed. So that's a good change.

But still we should do a test of detecting changes across the real Internet. Anyone want to hang out with me on Skype and do a manual test?

**Comment by benjamin-heasly** [comment]
Thanks David.

I missed you at 10.  But here's a test script we can run asynchronously: [rdt_issue_65_test.m.zip](https://github.com/isetbio/RemoteDataToolbox/files/166044/rdt_issue_65_test.m.zip)

It has some code for "Person A" and some code for "Person B".

Would you like to be Person A and run the first section?  This will publish a new artifact.

Then I can run the next two sections as Person B.  This will make an update to the artifact.

Then you can finish up as Person A.  You should see my update.

**Comment by benjamin-heasly** [comment]
David and I rand this test script and had success: I updated an artifact that David had created.  The next time David read the artifact, he saw my update.
