### ISSUE TITLE
Running the RDT on the AWS/Jupyter system

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#74]
James and I installed the RemoteDataToolbox on the Notebook server.  Went great!  Some of it runs, which is very cool.

But when we tried to download an artifact we get this message which seems like a Ben level issue.

```
data = rd.readArtifact(a(1));
error status 1 (
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

)
```

Thanks ...

**Comment by benjamin-heasly** [comment]
Oh, good point.  I just checked and I see the error too.  I'll fix it for
our new server which I hope will be up and running today.

**Comment by benjamin-heasly** [comment]
This is fixed in our new server.

The problem was that the old server doesn't have Java installed.

So I'll close this.
