### ISSUE TITLE
A few changes pushed for testing

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#75]
I added a 'recursive' option to rd.listArtifacts so that 

  by default only the artifacts in the local path are returned
  by setting 'recursive',true the artifacts in this path and below are returned (previous behavior)

If 'print',true  and recursive is true, then the printout separates the local from the sub-path artifacts.

The behavior was helpful to me in documenting; it is more like the behavior of ls in which we do a recursive ls by explicitly calling ls -R.  I am testing and open for comments and changes.

**Comment by benjamin-heasly** [comment]
This sounds like good behavior to me.

I would just want to check that our automated tests still work.  And if not, fix them to agree with the new behavior.

On my end, I see some of your related notes in the git log.  But I don't see the 'recursive' option in the code.  Should I look in a branch?

**Comment by wandell** [comment]
I screwed up the push.  I think it is on the site now.  

I not really happy with the 'recursive', which should probably sort by the (sub) remote path.  But at least it is there now.

Thanks

**Comment by benjamin-heasly** [comment]
I ran the automated tests and updated them to make use of the new "recursive" parameter.

So for now I think LGTM.

**Comment by wandell** [comment]
Thanks.  Let's close this.  
Today I am going to start working with Jon Winawer on the management of MRI data using this tool.  Likely we will create additional issues.  But I am hopeful that this tool will serve that community, as well.

Onward!
