### ISSUE TITLE
Publishing a zip file

### ISSUE THREAD

**Issue by JWinawer** [isetbio/RemoteDataToolbox#76]
I would like to publish a zip file to the vistasoft repository. I am getting an error. The zip file is called _ernieFreesurfer.zip_and was in my local Matlab path. Can someone advise? My code and the error are below.

```
% Create remote data toolbox object
rd = RdtClient('vistasoft');

% To write to the archive, you must have a password
rd.credentialsDialog;

% Act with lots of printouts
rd.configuration.verbosity=0;

% Theses are the paths on the remote data server
p = rd.listRemotePaths;

% Change the remote path
rd.crp('/vistadata/anatomy/');

% Publish the ernie freesurfer directory in the anatomy directory.
rd.publishArtifacts('ernieFreesurfer.zip','type','zip');
```

This was the result:
`Error using gradlePublishArtifact (line 110)
error status 1 (Starting a new Gradle Daemon for this build (subsequent builds will be faster).
:generatePomFileForMavenPublication
:publishMavenPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':publishMavenPublicationToMavenRepository'.
  
  > Failed to publish publication 'maven' to repository 'maven'
  > Invalid publication 'maven': artifact file does not exist:
  > '/Users/jonathanwinawer/matlab/git/RemoteDataToolbox/external/gradle/ernieFreesurfer.zip/ernieFreesurfer.zip'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.741 secs
)

Error in rdtPublishArtifact (line 67)
[localPath, pomPath, type] = gradlePublishArtifact(configuration.repositoryUrl, ...

Error in rdtPublishArtifacts (line 133)
    artifactCell{ii} = rdtPublishArtifact(configuration, ...

Error in RdtClient/publishArtifacts (line 365)
            artifacts = rdtPublishArtifacts(obj.configuration, ...`

**Comment by benjamin-heasly** [comment]
Hi @JWinawer,

No problem.  I think the issue is that `publishArtifacts()` wants you to give it a folder name instead of a file name, and it is getting confused.  I think an absolute folder is what it needs.  Something like this:

```
% Publish the ernie freesurfer directory in the anatomy directory.
pathToDirectory = %fill in the path here
rd.publishArtifacts(pathToDirectory, 'type', 'zip');
```

Does that help?

**Comment by benjamin-heasly** [comment]
For reference and completeness, I'm attaching a script which I used to reproduce this error, and helped me figure out what to do about it.

[rdt_issue_76.zip](https://github.com/isetbio/RemoteDataToolbox/files/344176/rdt_issue_76.zip)

**Comment by JWinawer** [comment]
Excellent - worked perfectly. Thanks.
