### ISSUE TITLE
Failure to run on gray/SNI-VCS

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#78]
Hi Will,

We did some debugging and have isolated the problem with the RemoteDataToolbox on gray and sni-vcs (things run on black).  It concerns a urlread2() call in Matlab.  Since you set up gray and sni-vcs, we think are the best person to figure out how solve the problem.
1.  Please run Matlab and add the in ~wandell/github/RemoteDataToolbox to the default path.
2.  This code snippet breaks the system on gray and SNI-VCS, though it runs on black and all other machines we have configured.

%% Go get a white matter mask from the Remote Data client

rdt = RdtClient('vistasoft');
rdt.crp('/vistadata/diffusion/zippedDirectory');

% This is all of the artifacts
a = rdt.listArtifacts('print',true);

The problem is on line 94 of the function rdtRequestWeb, which is called from the listArtifacts function.  On that line, there is a urlread2() call with legitimate parameters (in our opinion).  The function simply freezes there, stopping Matlab.

It is best if you give this a try and check the parameters of the urlread2() to see why there is a problem on gray, when things work smoothly elsewhere.

It is important for us to make this toolbox work on many systems, and so far it has done fine.  From this we will learn something about the challenge in the way gray is configured and hopefully find a solution.

Thanks,
Brian

**Comment by benjamin-heasly** [comment]
@wandell I think you guys figured this out.  Is that so?  Do you think we have more work to track with this issue?

**Comment by wandell** [comment]
Yes.  Basically, sometimes I need to reboot my mac to make the java code know about my IP address.
